Yoast/yoast-acf-analysis

- js/yoast-acf-analysis.js
- readme.txt
- yoast-acf-analysis.php
Integrated recalculation filters (WordPress SEO 3.1).
Also applied Yoast code styles and added documentation.
Post and Term ACF fields are being added to the content in JavaScript and to the recalculation algorithms.
What does not work yet: wysiwyg ACF fields are not updated in JavaScript yet.
This will be a new issue.
> Integrate recalculate filters

- js/yoast-acf-analysis.js
In effect this plugin has been broken since WP 4.5 came out. This minor change fixes that.
References:
https://make.wordpress.org/core/2016/03/29/jquery-updates-in-wordpress-4-5/
https://wordpress.org/support/topic/read-this-first-wordpress-45-master-list?replies=7#post-8271654
> Fix js syntax errors for jQuery 1.12 which was included with WP 4.5.

- yoast-acf-analysis.php
Using Yoast SEO premium and this plugin results in blank tabs for social sharing. Enqueuing scripts in the footer fixes this issue.
> Avoid social share blank screen when using Yoast SEO Premium.

- js/src/app.js
- js/src/collect/collect.js
- js/src/replacevars.js
- js/yoast-acf-analysis.js
- tests/js/system/helpers/replaceVars.js
- tests/js/system/helpers/simpleField.js
- tests/js/system/nightwatch.json
- tests/js/system/pages/WordPressHelper.js
- tests/js/system/tests/acf5/basic.js
- tests/js/system/tests/general/basic.js
- tests/js/system/tests/general/content.js
Allows usage of fields added by ACF in the Snippet Window.
The fields can be used with %%cf_{name-of-custom-field}%%
This fixes Yoast/wordpress-seo#5632.
This depends on Yoast/wordpress-seo#7607 as it uses the exposed `ReplaceVar` class but will fail gracefully ( not do anything ) if it's not present.
> Add support for replacement variables in the Snippet Window.

- js/src/app.js
- js/src/helper.js
- js/src/scraper/scraper.taxonomy.js
- js/yoast-acf-analysis.js
- tests/js/system/tests/acf5/relational.js
> fix select2 problem with taxonomy scraper

- inc/class-ac-yoast-acf-content-analysis.php
- inc/class-yoast-acf-analysis-assets.php
- readme.txt
- tests/php/unit/AssetsTest.php
- tests/php/unit/MainTest.php
- yoast-acf-analysis.php
Reusing constants and base-classname will provide better backwards-compatiblity
Fixes https://github.com/Yoast/yoast-acf-analysis/issues/27
> Use the constants used in the AC plugin

- yoast-acf-analysis.php
User who has no rights to manager plugins:
User who has rights to manage plugins:
After installing the Angry Creative plugin, suggest to deactivate and remove this plugin:
I have chosen not to deactivate the plugin automatically, because it will still leave the plugin files in place. These should be removed for security reasons.
Fixes https://github.com/Yoast/yoast-acf-analysis/issues/28
> Introduce messages to inform the user about deprecation

- languages/acf-content-analysis-for-yoast-seo.pot
Updates the pot file to the changed text domain and copy.
As the textdomain has been updated in the upcoming release, the filename of this file had to be updated. Incorporates the latest copy changes.
In the next release we can verify that all translations are working as expected on translate.wordpress.org. If verified we can remove the `.pot` file and manual loading of the translations from the plugin as this is automatically done in WordPress 4.6+.
Fixes https://github.com/Yoast/yoast-acf-analysis/issues/53
> Updated the pot file

- js/src/scraper/scraper.taxonomy.js
- js/yoast-acf-analysis.js
- tests/js/system/tests/acf5/relational.js
fixes #79 
This could probably still be improved as the case of ACF5 with select2 v3 is now not actually covered by the tests. But for that I am waiting for #103 because it will add the infrastructure to add a CPT for which we could then switch select2 to v3.
> Determine select2 version from ACF instead of guessing from ACF version

- tests/js/system/nightwatch.json
As this can be used without making use of the custom VVV testing environment, using a default VVV domain seems only logical.
The `nightwatch.config.example.js` now contains a replacement string, which will be filled with the actual domain when the VVV testing environmnet IS used. This will overwrite the domain configured here.
> Convert launch URL to more general domain

- js/src/app.js
- js/yoast-acf-analysis.js
The refactoring in #116 calls the wrong listeners. So changes don't trigger updates any more. This also broke all JS tests.
> Fix inverted listeners

- composer.json
- inc/class-ac-yoast-seo-acf-content-analysis.php
- tests/js/system/data/test-data-loader.php
- yoast-acf-analysis.php
As noticed in #103 it is not ideal to handle the loading of testing data inside the production plugin code as said in #111.
I've been thinking about several approaches: This PR proposes the one I like the most.
* No code left in Plugin itself
* Load dev bootstrap with composers [autoload/files functionality](https://getcomposer.org/doc/04-schema.md#files)
* Use normal composer autoloader with PHP 5.3.2+ as [`xrstf/composer-php52`](https://github.com/composer-php52/composer-php52) apparently doesn't support the `files` autoload functionality, hence this only works with PHP 5.3.2+. But as this is only needed for client-side tests those shouldn't really care about the PHP version in use.
* Adds hooks before WP is initialized by adding a hook to  `global $wp_filter`
This PR can be tested by …
> Remove testing code from plugin

- readme.txt
* _N/A_
* The `text-domain` tag should be at the top of the plugin file, not the readme (where it already is).
* Adds the new `Requires PHP` tag.
> README: fix header tags

- yoast-acf-analysis.php
* Prevent conflicts with other plugins/themes.
This variable is defined in the global namespace with a dangerously generic name.
Changing the variables name can be regarded as a backward-compatibility break, albeit very minor, however, leaving the name as it is can be considered a bug.
* The plugin should still load as expected.
> CS/QA: rename a global variable

- tests/php/unit/Configuration/StringStoreTest.php
_N/A_
* No functional changes.
* Code style compliance. Compliance with the `Squiz.Strings.DoubleQuoteUsage` sniff.
Using double quotes is marginally slower than single quotes as PHP will try and find interpolated variables in the string. Whenever reasonable, using single quotes is preferred.
Valid use cases for double quoted strings:
* When there is an interpolated variable
* When the string contains single quotes
_N/A_
> CS: fix unnecessary usage of double quotes

- yoast-acf-analysis.php
* Improved compatibility with PHP 7.2+.
* Security hardening.
* Prevent conflicts with other plugins/themes.
* Prevent a potential fatal error.
This minor refactor actually solves four problems:
* PHP 7.2+ compatibility - `create_function()` has been deprecated and will be removed in PHP 8.0.
* The variable `$message` was a global variable which, considering its generic variable name, could lead to unexpected results if/when other plugins/themes would also use that variable.
* `$message` was not being escaped for output which - if the variable would have been hijacked by another plugin/theme could have led to a hacked admin interface.
* The original conditional `! class_exists( 'AC_Yoast_SEO_ACF_Content_Analysis' ) && is_admin()` …
> QA: refactor code to remove usage of `create_function()`

- tests/php/unit/Doubles/failing-dependency.php
- tests/php/unit/Doubles/passing-dependency.php
- tests/php/unit/requirements-test.php
* _N/A_
* Put the helper classes for the `Requirements_Test` each in a separate file in a new `Doubles` directory.
* Verify that the unit tests are still run & pass.
> Best practices: only one class per file

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/requirements-test.php
* _N/A_
* Tests: always keep the `setUp()` and `tearDown()` methods together
... to make it easy for other devs to verify that any fixtures which are setup are also torn down.
* Documentation: add perfunctory documentation to test `setUp()`/`tearDown()` methods
* _N/A_
> Tests: safeguard setup teardown method consistency

- .phpcs.xml.dist
- composer.json
- composer.lock
- inc/assets.php
- inc/configuration/configuration.php
- inc/configuration/string-store.php
- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-interface.php
- inc/dependencies/dependency-yoast-seo.php
- inc/registry.php
- inc/requirements.php
- tests/js/system/data/test-data-loader-functions.php
- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Doubles/failing-dependency.php
- tests/php/unit/Doubles/passing-dependency.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
* _N/A_
This updates:
* PHP_CodeSniffer from v 3.3.0 => 3.3.1
* WordPressCS from v 0.14.1 => 1.0.0
* PHPCompatibility from v 8.1.0 => 8.2.0
This adds:
* PHPCompatibilityWP at v 1.0.0
The following dependencies of PHP Mess Detector, which is part of YoastCS, have also been updated:
* Symfony Polyfill Ctype from v 1.8.0 => 1.9.0
* Symfony Filesystem from v 3.4.11 => 3.4.14
* Symfony Dependency Injection from v 3.3.17 => 3.3.18
* Symfony Config from 3.4.11 => 3.4.14
Additionally, the Roave Security Advisories have been brought up to date.
* Remove a directive which has to do with a bug in WPCS which has been fixed in version 1.0.0.
* Remove a directive which has to do with a bug in PHPCS which has been fixed in version 3.3.1.
This …
> PHPCS: Update to use YoastCS 1.0 / WPCS 1.0

- composer.json
- tests/php/phpunit.xml.dist
* _N/A_
Looks like PR #142 inadvertently disabled the unit tests as the test files are no longer PSR-4 compliant and the name suffix check done by PHPUnit may or may not be case-sensitive. Mea culpa.
These minor changes should re-enable them.
Note: The `acf.php` dummy file is explicitly excluded from being autoloaded as the `Yoast_ACF_Analysis_Dependency_ACF` class does a [`class_exists()` without setting the `$autoload` parameter](http://php.net/manual/en/function.class-exists.php) to `false`.
As this may actually be advantageous in a situation were WP plugins are being installed via Composer, I've elected not to change that function call, but to exclude the test dummy file from the autoload class map instead.
This PR can be …
> Travis: re-enable running the unit tests

- .phpcs.xml.dist
- .travis.yml
- composer.json
- composer.lock
- inc/configuration/string-store.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
- yoast-acf-analysis.php
* Includes adding the PHPCS XSD to the custom ruleset which should now be valid as the minimum PHPCS requirement has gone up to PHPCS 3.3.2.
* Includes removing the DealerDirect Composer PHPCS plugin which now comes automatically with YoastCS.
... to comply with WPCS 1.1.0.
This PR addresses some inconsistencies related to deprecated functions. It basically applies the following rules:
* Deprecated functions/methods should be at the end of the file/class.
* They should be preceded by a `/* *** DEPRECATED METHODS/FUNCTIONS *** */` delimiter to clearly indicate the start of the deprecated functions.
* Deprecated functions should be ignored for the purposes of calculating code coverage via PHPUnit and therefore should each have a `@codeCoverageIgnore` tag in their docblock.
As PR #163 fixed …
> Update to yoastcs 1.1.0

- grunt/config/eslint.js
- inc/configuration/configuration.php
- js/src/collect/collect.js
- js/src/scraper-store.js
- js/src/scraper/scraper.text.js
- js/src/scraper/scraper.textarea.js
- js/yoast-acf-analysis.js
- tests/php/unit/Configuration/configuration-test.php
* Introduces a new filter to adjust field order, which also adds the possibility to prepend field content to WordPress' `post_content` using a negative field order.
* Wraps textarea and non-headline text content in paragraphs.
*
**First and foremost: Ensure you have ACF installed in addition to this plugin. Also, testing this in your dev environment will allow you to properly see what's being logged in your browser's console.**
To test the filter:
* Add a few custom fields and make sure to copy/ write down their IDs.
* Call the `yoast-acf-analysis/field_order` filter (`functions.php` in your current theme could be a good place to do this) and pass along an array where the IDs are …
> Introduce new filter to adjust field order

- .phpcs.xml.dist
- composer.json
- composer.lock
* _N/A_
Updates the CS requirements to YoastCS 1.2.2, including updating the dependencies.
No changes to the code are needed.
The selective exclusion for namespaced files without file comment can now be removed as YoastCS 1.2.0+ has a sniff which takes that into account.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/1.2.0
* https://github.com/Yoast/yoastcs/releases/tag/1.2.1
* https://github.com/Yoast/yoastcs/releases/tag/1.2.2
* Either do a `composer install` and then a `vendor/bin/phpcs` òr check the Travis logs for the CS run to verify that all is well.
> Composer: require YoastCS ^1.2.2

- .gitignore
- composer.json
- phpunit.xml.dist
* _N/A_
> If `phpunit.xml` or `phpunit.xml.dist` (in that order) exist in the current working directory and `--configuration` is not used, the configuration will be automatically read from that file.
From: https://phpunit.de/manual/6.5/en/organizing-tests.html#organizing-tests.xml-configuration
In other words, moving the `phpunit.xml.dist` file to the project root allows for running PHPUnit without passing `--configuration` and makes it more obvious that there are unit tests associated with the PHP code in this plugin.
Includes adding `phpunit.xml` to the `.gitignore` file to allow devs to use that file for their own custom configuration.
* Check the Travis output to verify that the …
> PHPUnit: Move the config file

- .phpcs.xml.dist
- composer.json
- composer.lock
- phpunit.xml.dist
- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* _N/A_
The unit tests for ACF have a minimum PHP requirement of PHP 5.6 due to the dependency on BrainMonkey.
At this time, the only PHPUnit version supported was PHPUnit 5.x. However, as the minimum PHP requirement is 5.6 anyway, it is quite easy to make the unit tests compatible with PHPUnit 5.x - 7.x.
PHPUnit 5.x will run on PHP 5.6 - 7.1.
PHPUnit 6.x will run on PHP 7.0 - 7.2.
PHPUnit 7.x will run on PHP 7.1 - 7.3.
For now, PHPUnit 7.x will also work fine for PHP 7.4 (unstable), so supporting PHPUnit 8.x is not yet necessary.
Ref: https://phpunit.de/supported-versions.html
Background:
The classes in PHPUnit have been renamed to namespaced classes.
The namespaced alias for the TestCase class is available as of PHPUnit 5.4 and …
> QA: Make the unit tests PHPUnit cross-version compatible

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/main-test.php
* _N/A_
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available have been extended  hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the Yoast ACF Analysis plugin.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* …
> QA: use the most specific PHPUnit assertion possible

- .travis.yml
* _N/A_
The unit tests for the ACF plugin are not dependent on WP being loaded as `Brain\Monkey` is used to mock WP, so there is no need to download and install WP during the CI run.
* Check the Travis output to verify that the unit tests are still being run and pass.
> Travis/Unit tests: remove WP download

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* _N/A_
* Minimalist `@covers` tags to ensure that incidental code coverage will not be recorded.
At some point in the future, these _could_ be improved by having `@covers` tags at method level instead of at class level.
* _N/A_
> CS/QA: add minimalist @covers tags to all tests

- .phpcs.xml.dist
- composer.json
- composer.lock
* _N/A_
Ruleset updates:
* Remove dependencies related `exclude-pattern`. These are now contained within the YoastCS ruleset as of v1.3.0.
* Remove the `languages` directory `exclude-pattern`.
The languages directory contains no PHP files, so there is no need to explicitly exclude it.
* Remove the `minimum_supported_wp_version` `config` directive. As of YoastCS 1.3.0, a default is set in the `Yoast` ruleset and should be followed by this repo.
The default in the `Yoast` ruleset at this time is `4.9`.
* Add the `yoast_acf` prefix (as proscibed for the `WordPress.NamingConventions.PrefixAllGlobals` sniff) to the list of prefixes which should be removed from filenames.
* Minor spelling fix in inline documentation.
This PR can be …
> Composer: require YoastCS ^1.3.0 & update ruleset

- .phpcs.xml.dist
- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
* _N/A_
WordPressCS will demand long arrays and forbid the use of short arrays as of WPCS 2.2.0.
See: https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
For YoastCS, however, a choice has been made to demand short arrays.
For now, while WP 4.9, and therefore PHP 5.2 still needs to be supported, this is only possible in the directories containing files with PHP 5.6+ code.
So in this interim period, we will enforce short arrays in the PHP 5.6+ code and long arrays everywhere else.
Once the minimum supported WP version has moved up to WP 5.2 / PHP 5.6, short arrays will be enforced for all code and the change-over can be done automatically using the auto-fixer included in the relevant sniff.
This PR can be …
> CS: enforce consistent array format

- composer.lock
* _N/A_
Mockery `1.2.2` has issues with PHP 7.4 which have been fixed in Mockery `1.2.4` (though not mentioned in the changelog).
Ref: https://github.com/mockery/mockery/releases
* If the PHP 7.4 build no longer fails and the tests are run, we're good.
> Update Mockery for testing on PHP 7.4

- .travis.yml
- composer.json
- composer.lock
- readme.txt
- yoast-acf-analysis.php
* _N/A_
Includes:
* Adjusting the `Requires...` info in the `readme.txt` file.
* Removing builds against PHP < 5.6.
* Removing the build against PHP 7.4 from allowed failures.
* Adding (back) a build against PHP `nightly` (PHP 8).
For now, this build will only lint the code. Unit testing is not yet possible with the current setup.
* Removing the `xrstf/composer-php52` dependency and references to the `vendor/autoload_52.php` file.
As the YoastSEO ACF unit tests are already passing without problem on PHP 7.4, these changes can already be made and made in one go.
Also:
* Travis hasn't supported `sudo` for quite a while now, so removing it.
Related to https://github.com/Yoast/wordpress-seo/issues/13758
This PR can be tested by …
> Stop explicit support for PHP < 5.6 / WP < 5.2

- .phpcs.xml.dist
- composer.json
- composer.lock
- inc/ac-yoast-seo-acf-content-analysis.php
- inc/assets.php
- inc/configuration/configuration.php
- inc/configuration/string-store.php
- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-yoast-seo.php
- inc/facade.php
- inc/registry.php
- inc/requirements.php
- readme.txt
- tests/js/system/data/test-data-loader-functions.php
- tests/php/unit/Configuration/configuration-test.php
* Deprecates `Yoast_ACF_Analysis_Facade::get_filter_name()`. Use hard-coded hook names instead.
* This deprecates the  `yoast-acf-analysis/config` filter hook in favour of the `Yoast\WP\ACF\config` hook.
* This deprecates the `yoast-acf-analysis/headlines` filter hook in favour of the `Yoast\WP\ACF\headlines` hook.
* This deprecates the `yoast-acf-analysis/blacklist_type` filter hook in favour of the `Yoast\WP\ACF\blacklist_type` hook.
* This deprecates the `yoast-acf-analysis/blacklist_name` filter hook in favour of the `Yoast\WP\ACF\blacklist_name` hook.
* This deprecates the `yoast-acf-analysis/scraper_config` filter hook in favour of the `Yoast\WP\ACF\scraper_config` hook.
* This deprecates the …
> PHPCS: Update to YoastCS 2.0.0

- inc/assets.php
* _N/A_
`$pagenow` is not used in the function.
* _N/A_
> QA: remove unused variable import

- inc/dependencies/dependency-yoast-seo.php
* _N/A_
As `version_compare()` can return boolean when the third parameter is used, there is no need for the compare here anyway.
* _N/A_
> QA: don't use yoda conditions

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/Doubles/failing-dependency.php
- tests/php/unit/Doubles/passing-dependency.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
> QA: add missing import `use` statements for classes

- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
* _N/A_
Use fully qualified names for global functions to bypass PHP searching within the namespace first.
* _N/A_
> QA: use FQN functions in namespaced files

- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/assets-test.php
* _N/A_
Use fully qualified names for global constants to bypass PHP searching within the namespace first.
* _N/A_
> QA: use FQN constants in namespaced files

- inc/assets.php
- tests/php/unit/Configuration/string-store-test.php
* Code consistency
Don't use FQN in docblocks. Use unqualified names instead.
If the file is namespaced and the docblock comment involves a class from another namespace and no `use` statement is in place yet, add an import `use` statement.
Note: PHPUnit `@covers` tags *should* still be fully qualified (PHPUnit requirement)
* _N/A_
> CS: don't use FQN in docblocks

- js/src/collect/collect-v5.js
- js/src/replacevars.js
- js/src/scraper-store.js
- js/src/scraper/scraper.block_preview.js
- js/yoast-acf-analysis.js
Proof of concept that ACF block previews can be passed to Yoast SEO.
* Add support for ACF blocks
* Passes the complete block preview to Yoast SEO.
This means that in selected mode (when the preview is visible and the edit fields are visible in the sidebar), the content is passed twice to Yoast SEO. This needs a solution.
* Create a custom Gutenberg block using ACF (See [ACF blocks](https://www.advancedcustomfields.com/resources/blocks/))
* Add the custom block to a post
* Check that content is being passed to Yoast SEO by watching the debug info or the changing Yoast recommendations.
Fixes #241
> ACF blocks support

- js/src/collect/collect-v5.js
- js/yoast-acf-analysis.js
* Fixes a bug where using the classic editor caused an error due to not finding the block editor.
* N/A
* Follow the reproduction steps in https://yoast.atlassian.net/browse/QAK-1866 and verify that you cannot reproduce using this PR.
* Verify that for example the keyword density SEO check updates correctly using custom fields.
> Conditionally look for fields in metabox normal, side, or blocks

- inc/assets.php
* Compatibility with Yoast SEO 14.2 JavaScript changes. We used to depend on JavaScript files which aren't there anymore. We now depend on post-edit.js or term-edit.js.
* In https://github.com/Yoast/wordpress-seo/pull/15083, Yoast SEO consolidates to less JavaScript files per screen.
* Checkout the `script-data` branch on Yoast SEO or `trunk` if the PR is merged already. 
* See the current stable of Yoast ACF doesn't load its JavaScript anymore.
* Checkout this PR. See it works again.
> Rely on post-edit and term-edit instead of post-scraper and term-scraper

- inc/dependencies/dependency-yoast-seo.php
* The minimal required version for Yoast SEO is now 14.5.
* Changes made to localized scripts/objects in Yoast SEO required compatablity changes (made in https://github.com/Yoast/yoast-acf-analysis/pull/247 ). These changes mean that Yoast ACF Analysis only works with Yoast SEO 14.5 and onward.
> bump version to 14.5

- inc/dependencies/dependency-yoast-seo.php
- readme.txt
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
* Set minimum Yoast SEO version to 14.6.
* The planned release date for Yoast ACF 2.5 was together with Yoast SEO 14.5, because the refactor that resulted in the higher minimum Yoast SEO version would be released in 14.5. However, that refactor has moved to 14.6.
*
Fixes #
> Set minimum Yoast SEO version to 14.6

- js/src/collect/collect-v5.js
- js/yoast-acf-analysis.js
Previously, only ACF block which were set to preview mode (the default mode) were communicated to Yoast SEO. However, any block mode can switch to the preview state, either automatically or manually, in the block editor. This patch just checks if such a preview exists, instead of relying on the block being in one of the modes.
* Fixes a bug where the content of ACF blocks in 'auto' mode was not taken into account when the block (automatically) switched to preview mode. Props to [TimVevida](https://github.com/TimVevida)
During testing, I found that the order of the content passed to Yoast SEO can vary, blocks in the edit state are added as individual fields earlier in the process. Because the best results are achieved when all …
> Detect ACF blocks in preview, regardless of display mode

- grunt/config/eslint.js
- inc/assets.php
- js/src/app.js
- js/yoast-acf-analysis.js
- tests/php/unit/assets-test.php
* Fixes a bug where changes to the content of the ACF fields didn't trigger a live refresh ot the Yoast SEO analysis.
1. I'm using the new ACF JavaScript API introduced in ACF 5.7: https://www.advancedcustomfields.com/resources/javascript-api/
2. **important: this means the new code is not compatible with previous ACF versions** (the current version is 5.9.1)
3. I'm using the `acf.Model` API with an `input` event: this event fires for changes to _any_ native form element including checkboxes, radio buttons, select elements. Changing the value of these form elements will trigger an analysis refresh even if, actually, there's no change in the post content. I opted to not filter out these form elements to keep things simple and …
> P3-147 Fix refresh analysis

- inc/dependencies/dependency-acf.php
* Doesn't activate the plugin if ACF < 5.7 is detected.
*
* Install ACF < 5.7.
* Try to activate the ACF for Yoast Plugin.
* See a notice on top of your screen:
* Note that the plugin still looks activated in the overview. However, it's not doing anything in the editor. This is consistent with what happens when you haven't ACF installed at all. If you have installed ACF 5.0-5.6, this means there won't be console errors in the editor saying `acf.Model is not a constructor`.
* Install ACF > 5.7.
* Don't see a notice
* Verify that the plugin does its thing in the editor.
Fixes #
> Don't activate the plugin if ACF < 5.7 is running

- composer.json
- composer.lock
- inc/assets.php
* Updated dependencies
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/2.1.0
* …
> Composer: update YoastCS and Composer Installers

- composer.json
- composer.lock
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
* Updated test dependencies
Updated:
* BrainMonkey from v 2.4.0 to 2.5.0.
Note: this version contains a test breaking change which will be addressed in a subsequent commit if applicable for this repo.
* Mockery from v 1.3.0 to 1.3.3.
Improved support for PHP 8.
* Hamcrest-php from v 2.0.0 to 2.0.1
... which claims compatibility with PHP 8.
* Patchwork from v 2.1.11 to 2.1.12
This fixes [two issues](antecedent/patchwork#99) which _might_ be relevant for us.
Refs:
* https://github.com/Brain-WP/BrainMonkey/releases
* https://github.com/mockery/mockery/releases
* https://github.com/hamcrest/hamcrest-php/releases
* https://github.com/antecedent/patchwork/releases
The WP native `has_filter()` and `has_action()` functions return a …
> Composer: update BrainMonkey with dependencies

- .gitignore
- .travis.yml
- composer.json
- composer.lock
- phpunit.xml.dist
- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* Preparation for compatibility with PHP 8
Replaces earlier PR #278
* Adds a dev dependency to the `yoast/wp-test-utils` package, which will also make the PHPUnit Polyfills available.
* As that package already requires and manages the installable versions for BrainMonkey and PHPUnit, remove these as explicit requirements from `require-dev` in favour of letting the WP Test Utils package manage the versions.
The install is done based on PHP 5.6 and includes updating the dependencies from PHPUnit itself within the constraints of maintaining compatibility with PHP 5.6.
This new package adds the following features:
* Polyfills for various PHPUnit cross-version changes.
* Basic test cases for use by the plugins.
Refs:
* …
> Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8

- js/src/main.js
- js/yoast-acf-analysis.js
* Fixes a bug where ACF Analysis would fail on term pages.
* This is a load order problem. In the `term-scraper` of Yoast SEO we still use `jQuery( document ).ready`. 100ms should be enough to run after the term-scraper initialization. Alternatively we could remove jQuery ready there. Resulting in both "only" using WP's `domReady`, which would work too.
1. Install and activate the following plugins on WordPress 5.6: Yoast SEO 15.4, ACF Content Analysis for Yoast SEO 3.0 and Advanced Custom Fields 5.9.3
2. Configure ACF to show a custom text field on taxonomy forms (see screenshot in issue)
3. Open the browser console and visit a taxonomy edit page
4. Notice the error is no longer in …
> QAK-2538 hotfix error on term pages

- .travis.yml
- composer.json
- composer.lock
* Update CI/test environment
Update WP Test Utils to version 0.2.1 with dependencies, ~~which means that BrainMonkey and PHPUnit Polyfills have now also been updated~~.
Refs:
* https://github.com/Yoast/wp-test-utils/releases/tag/0.2.0
* https://github.com/Yoast/wp-test-utils/releases/tag/0.2.1
Since this Friday, Travis now has a PHP 8.0 image available.
This commit:
* Adds a new build against PHP 8.0, with `PHPUNIT` flag set to `1` (= on), which is not allowed to fail.
* No longer run the tests against `nightly` (PHP 8.1), only lint the code on `nightly`.
* In the `install` section: makes sure that the `composer install` with `--ignore-platform-reqs` is used for PHP 8.x as otherwise the install would fail due to PHPUnit 5.x (as …
> Update WP Test Utils, BrainMonkey and add PHP 8.0 to the Travis matrix

- composer.json
- composer.lock
* Updates dev tools
WP Test Utils 1.0.0 provides cross-version compatibility with the test setup from WP < 5.9 and WP 5.9+.
Includes updating the dependencies of WP Test Utils.
Refs:
* https://github.com/Yoast/wp-test-utils/releases/
* https://github.com/Yoast/PHPUnit-Polyfills/releases/
* https://github.com/mockery/mockery/releases/tag/1.3.5
* https://github.com/antecedent/patchwork/releases
* _N/A_ If the build passes, we're good.
> Composer: update to WP Test Utils 1.0.0

- .github/workflows/cs.yml
- .github/workflows/js.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
* Improve CI
... so builds against PHP 8.1 should no longer be allowed to fail.
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/
(used in inline script documentation) 
* _N/A_ If the build passes, we're good.
> GH Actions: minor tweaks

- .github/workflows/js.yml
* Update CI
The `setup-node` action has released a new major.
This upgrades the JS workflow to use this new action runner.
Ref: https://github.com/actions/setup-node/releases/tag/v3.0.0
* _N/A_ If the build passes (and the deploy after the merge succeeds), we're good.
> GH Actions: update setup-node action runner

- .github/workflows/cs.yml
- .github/workflows/js.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/test.yml
* Improve CI
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* _N/A_ If the build passes, we're good.
> GH Actions: version update for various predefined actions

- .github/workflows/cs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
* CI maintenance
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like …
> GH Actions: various tweaks

- .github/workflows/lint.yml
- .github/workflows/test.yml
- composer.json
- composer.lock
- readme.txt
- yoast-acf-analysis.php
* 
* Drops compatibility with PHP 5.6, 7.0 and 7.1.
* Note that this addon doesn't have any requirement to Yoast SEO so we won't need to update any reference to the Free feature branch.
* Verify the GH actions pass
* install on a PHP 5.6 environment
* visit the Plugins page
* see that you get the same message and you can't activate the plugin, as it happens here for Free and Premium:
* the same should happen with 7.0 and 7.1
**note**: the above may be tricky to test. I can see 5.6 as a choice in Local by Flywheel, but I know it's not the case for others (and I can see 7.0 an 7.1 are not available - neither 7.2 actually)
I tried on Instawp, where you have the full choice …
> Drop compatibility with PHP 5.6, 7.0 and 7.1

- .github/workflows/test.yml
- .gitignore
- README.md
- composer.json
- phpunit.xml.dist
* Enable test code coverage monitoring.
This commit makes the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` worflow to run the high/low PHP version builds with code coverage and upload the results.
* Updating the PHPUnit config to show an inline code coverage summary and provide the logging needed for Coveralls.
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding a script to the `composer.json` file to run code coverage.
* Adding a code coverage badge to the README.
Notes:
* Coverage will be recorded using `Xdebug` as the code coverage driver.
* Recording code coverage can be …
> CI/QA: start recording code coverage

- tests/php/unit/Configuration/configuration-test.php
* Test improvements
Fix incorrect parameter order in test assertions, which makes debugging harder.
The first parameter for `assertSame()` is the `$expected` value, the second should be the _actual_ value, like retrieved via a function call.
* _N/A_ If the tests pass, we're good.
> CS/QA: fix incorrect parameter order in test assertions

- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-yoast-seo.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
* Sets the minimum required Yoast SEO version to 20.8.
* Sets the minimum required ACF version to 6.0.0.
*
* Install with Yoast 20.8-RC* and ACF 6.* and see you don't get any notice
* Install with Yoast 20.7 and see you get a notice "Please upgrade the Yoast SEO plugin to the latest version to allow the ACF Content Analysis for Yoast SEO module to work."
* Install with ACF 5.* and see you get a notice "ACF Content Analysis for Yoast SEO requires ACF (free or pro) 6.0.0 or higher to be installed and activated."
* Install without Yoast SEO and see you get a notice "ACF Content Analysis for Yoast SEO requires Yoast SEO to be installed and activated."
Fixes #
> Fix required version numbers

- composer.json
- composer.lock
* Tidy up `composer.json` file and improve usability of scripts
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
This script has been superseded by the Composer plugin handling this automatically.
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: …
> Composer: normalize the file, add script descriptions, remove redundant script

- phpunit.xml.dist
* Dev-file update
PHPUnit config: update schema reference to the minimum PHPUnit version which is currently in use.
The configuration has also been validates against the schema and where needed, updated.
* _N/A_
> PHPUnit config: update schema reference

- composer.json
- composer.lock
* Users requiring this package via [WP]Packagist can now use the `composer/installers` v2.
While the latest version of the `composer/installers` package is `2.2`, I'm explicitly setting the version constraint to a lenient one as this is a non-`dev` requirement, which comes into play when people use a [WP]Packagist based site setup.
If we set the requirement very strictly, it could conflict with other plugins with different constraints and it is not as if any of the 2.x releases have touched the WordPress installer, so setting it to `|| 2.0` should be fine.
* _N/A_
> Composer: allow composer installers 2.x

- .phpcs.xml.dist
- tests/Unit/Assets_Test.php
- tests/Unit/Dependencies/Dependency_Yoast_SEO_Test.php
* Test tweak
Use PHPUnit annotations instead of properties.
Apparently this must have worked in some way, but the `preserveGlobalState` for the `DependencyYoastSEOTest` was definitely not correct (and probably not working either).
* _N/A_ If the builds pass, we're good.
> Tests: use PHPUnit annotations

- composer.json
* QA
CLI arguments should either be encoded in the config file or set by the dev-user. This is neither here nor there.
* _N/A_
> Composer: remove redundant CLI argument from scripts

- .gitattributes
- .github/workflows/cs.yml
- composer.json
- config/composer/actions.php
* CI/Composer scripts improvement
* CI/Composer scripts improvement
This adds a number of extra CS-related Composer scripts and handler functions.
This:
* Uses the same menu as is already in use in the Free, Premium and several other plugins for predictability.
* Where necessary, adjusts existing Composer scripts to, again, be in line with what is already in use in Free and Premium.
This also adds the _ability_ to run CS with a Threshold. As the codebase is currently clean, this ability is not activated for CI for the time being, though it is likely that it will be activated once YoastCS 3.0 will be used.
Note: this change does mean that, in contrast to before, running `check-cs` will now return only errors. While this is new for …
> Composer: implement CS menu and extra commands

- inc/assets.php
- inc/configuration/configuration.php
- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-yoast-seo.php
- inc/registry.php
- inc/requirements.php
- tests/Unit/Requirements_Test.php
- tests/js/system/data/test-data-loader-functions.php
- yoast-acf-analysis.php
* Code QA/consistency
* Code QA/consistency
* Docs: improve type specificity
* Docs: add missing return type void annotations 
* _N/A_ No functional changes.
> Docs: various updates

- .github/workflows/cs.yml
- .phpcs.xml.dist
- composer.json
- composer.lock
* CI/QA update introducing YoastCS 3.0
* CI/QA update introducing YoastCS 3.0
YoastCS 3.0.0 has been released and is based on WordPressCS 3.0.0.
This commit makes the necessary updates for that:
* Composer: update the requirements.
* PHPCS ruleset:
- Enforce strict PSR-4 for the tests.
- Remove some configuration which is now handled by YoastCS.
- Remove a few exclusions which are no longer needed.
* GHA CS workflow: run the CS check on the latest PHP version.
No need to run on PHP 7.4 any more as the deprecations previously encountered were all fixed.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/3.0.0
* https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/3.0.0
... instead of a full scan.
As there are …
> Composer/PHPCS: update to YoastCS 3.0.0

- .github/workflows/cs.yml
- composer.json
- composer.lock
- config/composer/actions.php
* Update dev dependencies
Nearly all dev dependencies have had new releases. This commit updates the plugin to use the new versions.
For linting, the upgrade will get us preliminary PHP 8.4 support.
For testing, the upgrades will get us continued support for running the tests via a PHAR file after the latest PHPUnit releases, as well as preliminary PHP 8.4 support.
For CS, the upgrades will get us improved syntax support for PHP 8.3, more documentation and a range of bug fixes.
This changes the implementation of the coding standards threshold check to require that both the `YOASTCS_THRESHOLD_ERRORS` environment variable, as well as the `YOASTCS_THRESHOLD_WARNINGS` environment variable match the current status exactly.
This …
> Composer: update dev dependencies

- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-yoast-seo.php
- yoast-acf-analysis.php
* Adds Premium notices to the new dashboard 
* This accompanies the respective Free PR: https://github.com/Yoast/wordpress-seo/pull/21644 
* Follow the test instructions of https://github.com/Yoast/wordpress-seo/pull/21644
Fixes https://github.com/Yoast/reserved-tasks/issues/269
> Move notices to new dashboard

- composer.json
- composer.lock
* Updated dependencies
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
Selectively update test dependencies to get us onto versions compatible with PHP 8.4.
Refs:
* https://github.com/antecedent/patchwork/releases/tag/2.2.0
* https://github.com/antecedent/patchwork/releases/tag/2.2.1
* https://github.com/Brain-WP/BrainMonkey/releases/tag/2.6.2
* https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.1.2
* https://github.com/sebastianbergmann/phpunit/blob/8.5.40/Chang …
> Composer: update various dependencies

- js/src/cache/cache.js
- js/yoast-acf-analysis.js
* Fixes a bug where browser performance was degraded by useless AJAX calls with an image or gallery field. Props to [mmorris8](https://github.com/mmorris8).
*
* Install and activate Free, ACF and this plugin
* create a new field group attached to posts
* add an image field and save the field group
* edit a post
* add an image in the image field
* keep the network tab open in the browser dev tools/inspector
* check the XHR calls
* **without this patch:**
* you should see a repeated call to `admin-ajax.php` with this data as request content: 
```
query[post__in][]: ""
action: "query-attachments"
```
* **with this patch:**
* you should not see a repeated call to `admin-ajax.php` with …
> Prevent repeated XHR calls with `query-attachments` action

- inc/dependencies/dependency-yoast-seo.php
- tests/Unit/Dependencies/Dependency_Yoast_SEO_Test.php
* Sets the minimum required Yoast SEO version to 24.6.
*
* NA
Fixes #
> Sets the minimum required Yoast SEO version to 24.6
