- yoast-acf-analysis.php
This PR solves a number of issues:
1. The js was only enqueued if the current user had the `activate_plugins` ability (=(super)-admin) rendering the plugin largely useless for multi-author websites where most authors are non-admins.
2. The requirements were checked using `is_plugin_active()` which is unreliable.
Changed this to a check based on code rather than on the `is_plugin_active()` function.
This is more reliable as:
a) it will also take into account plugins loaded through the must-use plugins directory
b) it will still work even if the user has renamed the folder for the plugin within `wp-content/plugins/` (which happens more often than you'd expect).
3. Allow for *this* plugin to be installed as a must-use plugin, i.e. the admin notice and the deactivation should only happen if …
> Improve requirements check.

- yoast-acf-analysis.php
Moved __FILE__ usage to define, this allows for class to be moved to own file in the future
Moved functionality to their own functions
Rewrote logic to make a little bit more sense
Show Yoast SEO notification before ACF (we are more important)
> Refactored to make it more readable

- js/yoast-acf-analysis.js
> Rebuild JS

- readme.txt
The version keyword has changed, see https://meta.trac.wordpress.org/ticket/2952#comment:5
> Change PHP version keyword

- inc/class-yoast-acf-analysis.php
- tests/php/unit/MainTest.php
> Ensure Configuration has right class

- tests/js/system/helpers/replaceVars.js
> Only run ReplaceVar tests when feature is available

- tests/js/system/pages/WordPressHelper.js
- tests/js/system/tests/acf5/content-pro.js
- tests/js/system/tests/general/content.js
Fixes #42 
@herregroen can you test if this works for you as you did change the test before.
> Fix test for Image Field

- README.md
- inc/dependencies/class-yoast-acf-analysis-dependency-afc.php
- inc/dependencies/class-yoast-acf-analysis-dependency-yoast-seo.php
- readme.txt
- yoast-acf-analysis.php
> update text domain and plugin name

- inc/class-yoast-acf-analysis-assets.php
- tests/php/unit/AssetsTest.php
regression introduced by #31
fixes #57
> fix path and test that has the same bug

- inc/configuration/class-yoast-acf-analysis-string-store.php
> Do not use short array syntax

- composer.json
At least fix the links if we're changing nothing else as discussed in #75
> fix .org links in composer.json

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Based upon the ones in the WordPress (Yoast) SEO repository.
> Add Github issue & PR templates

- inc/class-ac-yoast-acf-content-analysis.php
- package.json
> Add ACF 5 Free compatibility

- readme.txt
* Add filter examples to the readme.txt file
* Not applicable
* Not applicable
Fixes [#95](https://github.com/Yoast/yoast-acf-analysis/issues/95)
> Add filter examples to readme.txt

- composer.lock
Ran composer update on PHP 5.6
> Composer lock file for 5.6

- tests/js/system/nightwatch.conf.example.js
> Make the domain replacable by vvv provision script

- inc/class-ac-yoast-seo-acf-content-analysis.php
- inc/class-yoast-acf-analysis-assets.php
- inc/class-yoast-acf-analysis-facade.php
- inc/class-yoast-acf-analysis-registry.php
- inc/class-yoast-acf-analysis-requirements.php
- inc/configuration/class-yoast-acf-analysis-configuration.php
- inc/configuration/class-yoast-acf-analysis-string-store.php
- inc/dependencies/class-yoast-acf-analysis-dependency-acf.php
- inc/dependencies/class-yoast-acf-analysis-dependency-yoast-seo.php
- inc/dependencies/interface-yoast-acf-analysis-depencency.php
- tests/js/system/data/acf4.php
- tests/js/system/data/acf5.php
- tests/js/system/data/test-data-loader.php
- tests/php/unit/Dependencies/ACFClass.php
- yoast-acf-analysis.php
_N/A_
* No functional changes.
* Documentation CS compliance.
This PR will be easiest to review by looking at each commit individually.
**Take note**: for the test files containing namespaced classes, no file docblocks have been added as per https://github.com/Yoast/wordpress-seo-premium/pull/1536#issuecomment-354268808 /cc @atimmer 
_N/A_
> Documentation: various fixes

- tests/php/unit/Configuration/StringStoreTest.php
_N/A_
* No functional changes.
* Code style compliance.
As these are function local variables, these can be safely renamed to snake_case.
_N/A_
> CS: rename some local variables

- inc/ac-yoast-seo-acf-content-analysis.php
- inc/configuration/configuration.php
- inc/configuration/string-store.php
- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/Doubles/failing-dependency.php
- tests/php/unit/Doubles/passing-dependency.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* N/A
* Added missing documentation to various parts of the code, which were mostly tests.
*
Fixes #152
> Added missing documentation

- js/src/scraper/scraper.url.js
- js/yoast-acf-analysis.js
* Update url scraper to treat acf url field as outbound / internal links. Props to [t49tran](https://github.com/t49tran)
Fixes #
Fixed the issue mentioned in #192
> feat: update url scraper to treat url input content as link

- composer.json
- composer.lock
> Updated symfony/dependency-injection and sympfony/config

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/Configuration/string-store-test.php
- tests/php/unit/Dependencies/acf-dependency-test.php
- tests/php/unit/Dependencies/yoast-seo-dependency-test.php
- tests/php/unit/Doubles/failing-dependency.php
- tests/php/unit/Doubles/passing-dependency.php
- tests/php/unit/assets-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* _N/A_
* No functional changes.
* Code style compliance.
* _N/A_
This is a test-code-only change and should have no effect on the functionality. If the unit tests still run and pass, we're good.
> CS: fix namespaces of the unit tests

- tests/php/unit/requirements-test.php
> QA: remove unused `use` statement

- package.json
- yarn.lock
* None needed.
* Updated nightwatch, hope all still works.
*
Fixes #208
> Fix security issue with dependency

- tests/php/unit/Configuration/configuration-test.php
- tests/php/unit/main-test.php
- tests/php/unit/registry-test.php
- tests/php/unit/requirements-test.php
* Code style consistency
* Code style consistency
* _N/A_
> CS: order `use` statements alphabetically

- .travis.yml
* Replaces an archived vulnerability checker with the newer recommended package.
*
*
Fixes #
> P2-628-replace-security-checker

- readme.txt
* Sets minimum WordPress version to 5.9 and tested up to 6.0.
*
*
Fixes #
> Sets minimum WordPress version to 5.9 and tested up to 6.0.

- .github/CONTRIBUTING.md
- .github/workflows/cs.yml
- .github/workflows/js.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
* CI maintenance
* Make sure branch names in the branch selection are correct to ensure builds will still run when appropriate.
* _N/A_
> GH Actions: clean up after branch rename

- yoast-acf-analysis.php
* Updates the author uri value.
* Check if the `team yoast` url is the same as described in https://github.com/Yoast/wordpress-seo-premium/issues/3779
*
Fixes #
[3779](https://github.com/Yoast/wordpress-seo-premium/issues/3779)
> Updates author URI.

- readme.txt
- yoast-acf-analysis.php
* Sets the minimum supported WordPress version to 6.1.
*
* N/A
Fixes #
> Set the minimum supported WordPress version to 6.1

- composer.lock
* Update dev dependencies
Ref: https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.5
* _N/A_ If the tests run & pass, we're good.
> Composer: update PHPUnit Polyfills

- js/yoast-acf-analysis.js
- readme.txt
- yoast-acf-analysis.php
* Bumps ACF plugin version from 3.0.1 to 3.1
*
*
Fixes #
> Bump plugin version and update main javascript file

- phpunit.xml.dist
* Consistency
Tabs, not spaces.
* _N/A_
> CS: tidy up PHPUnit config file

- readme.txt
- yoast-acf-analysis.php
* Sets the minimum supported WordPress version to 6.2.
*
*
Fixes #
> Set the minimum supported WordPress version to 6.2.

- .github/workflows/cs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
* QA
* QA
Update a few links in inline comments as the old URLs are no longer valid.
* _N/A_
> GH Actions: update a few links in inline comments

- inc/dependencies/dependency-acf.php
- inc/dependencies/dependency-yoast-seo.php
* Code modernization
* Code modernization
*
* _N/A_ No functional changes.
> Modernize: add explicit visibility to all OO constants

- tests/Unit/Assets_Test.php
- tests/Unit/Configuration/Configuration_Test.php
- tests/Unit/Configuration/String_Store_Test.php
- tests/Unit/Dependencies/Dependency_ACF_Test.php
- tests/Unit/Dependencies/Dependency_Yoast_SEO_Test.php
- tests/Unit/Doubles/Failing_Dependency_Mock.php
- tests/Unit/Doubles/Passing_Dependency_Mock.php
- tests/Unit/Main_Test.php
- tests/Unit/Registry_Test.php
- tests/Unit/Requirements_Test.php
* Code QA/consistency
* Code QA/consistency
*
* _N/A_ No functional changes.
> Tests: make all classes either abstract or final

- tests/Unit/Configuration/Configuration_Test.php
* Code QA/consistency
* Code QA/consistency
*
* _N/A_ No functional changes.
> CS: minor fixes

- readme.txt
- yoast-acf-analysis.php
* Sets the minimum supported WordPress version to 6.3.
*
*
Fixes #
> Sets the minimum supported WordPress version to 6.3.

- readme.txt
- yoast-acf-analysis.php
* Sets the minimum supported WordPress version to 6.3.
*
*
Fixes #
> Sets the minimum supported WordPress version to 6.4.

- readme.txt
- yoast-acf-analysis.php
* Sets the minimum supported WordPress version to 6.5.
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21664
> Sets the minimum supported WordPress version to 6.5

- readme.txt
- yoast-acf-analysis.php
* Set the minimum supported WordPress version to 6.6.
*
* NA
Fixes #
> Set the minimum supported WordPress version to 6.6
